name: Build and Test in .NET and Angular

on:
  pull_request:
    branches: ["main"]
    types: [review_requested, reopened, synchronize]

jobs:
  dotnet:
    name: .NET Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  angular-web:
    name: Angular Build (Web)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: src/Btech_Front/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: src/Btech_Front

      - name: Test
        run: npm run test:ci
        working-directory: src/Btech_Front

      - name: Build
        run: npm run build
        working-directory: src/

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: docker compose build
